
# Data
# General config
variables:
  DBDriverClass : org.postgresql.Driver
  DBDialect : org.hibernate.dialect.PostgreSQLDialect

  showSQL : true

# Users' db credentials

  usersDBUrl : jdbc:postgresql://localhost:5432/monitoringappusersdb?useSSL=false&serverTimezone=UTC
  usersDBUsername : monitoringappusersdbdirector
  usersDBPassword : monitoringapp720130

# Data's db credentials

  dataDBUrl : jdbc:postgresql://localhost:5432/monitoringappdatadb?useSSL=false&serverTimezone=UTC
  dataDBUsername : monitoringappdatadbdirector
  dataDBPassword : monitoringapp720130
