
spring:

  # Core configs (Profiles)
  profiles:
    active: "dev"

  # Spring Data config
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  # User's db source
  auditors-datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/monitoringappusersdb?useSSL=false&serverTimezone=UTC
    username: monitoringappusersdbdirector
    password: monitoringapp720130

    driver-class-name: org.postgresql.Driver


  # Data's db sours
  data-datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/monitoringappdatadb?useSSL=false&serverTimezone=UTC
    username: monitoringappdatadbdirector
    password: monitoringapp720130

    driver-class-name: org.postgresql.Driver